import type { CSSProperties } from "react";
import { hexToRgba } from "@/lib/futureMe";
import type { FutureMeStyles } from "./types";
import type { Mood, ViewTab } from "@/lib/futureMe";

const PANEL_BORDER = "1px solid rgba(255,255,255,0.10)";
const GLASS_BG = "linear-gradient(145deg, rgba(24, 26, 38, 0.72), rgba(255,255,255,0.05))";
const TEXT_MAIN = "#ffffff";
const TEXT_MUTED = "rgba(255,255,255,0.62)";

export function createStyles(
  mobile: boolean,
  isPro: boolean,
  hasConversationStarted: boolean,
  loading: boolean,
  mood: Mood,
  accent: string,
  activeTab: ViewTab
): FutureMeStyles {
  return {
    page: {
      minHeight: "100dvh",
      height: "auto",
      overflowY: "auto",
      overflowX: "hidden",
      WebkitOverflowScrolling: "touch",
      padding: mobile ? 10 : 16,
      background:
        "radial-gradient(circle at 20% 10%, rgba(96,165,250,0.14), transparent 22%), radial-gradient(circle at 80% 12%, rgba(167,139,250,0.16), transparent 20%), radial-gradient(circle at 50% 90%, rgba(52,211,153,0.12), transparent 24%), linear-gradient(180deg, #09090d 0%, #0d0f16 100%)",
      color: TEXT_MAIN,
      fontFamily:
        'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      position: "relative",
    },
    shell: {
      minHeight: "100dvh",
      height: "auto",
      maxWidth: 1040,
      margin: "0 auto",
      display: "flex",
      flexDirection: "column",
      gap: 14,
      paddingBottom: 24,
      position: "relative",
      zIndex: 1,
    },
    glowA: {
      position: "fixed",
      inset: "12% auto auto -12%",
      width: 420,
      height: 420,
      borderRadius: 999,
      background: `radial-gradient(circle, ${hexToRgba(accent, 0.18)}, transparent 60%)`,
      filter: "blur(70px)",
      pointerEvents: "none",
      zIndex: 0,
    },
    glowB: {
      position: "fixed",
      inset: "auto -12% -14% auto",
      width: 540,
      height: 540,
      borderRadius: 999,
      background: "radial-gradient(circle, rgba(255,255,255,0.10), transparent 62%)",
      filter: "blur(90px)",
      pointerEvents: "none",
      zIndex: 0,
    },
    noiseOverlay: {
      position: "fixed",
      inset: 0,
      pointerEvents: "none",
      zIndex: 0,
      opacity: 0.055,
      backgroundImage: "radial-gradient(rgba(255,255,255,0.24) 0.7px, transparent 0.7px)",
      backgroundSize: "3px 3px",
      mixBlendMode: "soft-light",
    },
    topBar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      padding: "10px 10px",
      background: GLASS_BG,
      borderRadius: 24,
      border: PANEL_BORDER,
      boxShadow: "0 24px 64px rgba(0,0,0,0.34)",
      backdropFilter: "blur(30px) saturate(160%)",
    },
    hero: {
      borderRadius: 30,
      padding: mobile ? 22 : 32,
      background: GLASS_BG,
      border: PANEL_BORDER,
      boxShadow: "0 28px 72px rgba(0,0,0,0.34)",
      backdropFilter: "blur(34px) saturate(150%)",
      overflow: "hidden",
      position: "relative",
      transition: "all 420ms ease",
    },
    heroShine: {
      position: "absolute",
      inset: "-30% -10% auto auto",
      width: 320,
      height: 320,
      borderRadius: 999,
      background: `radial-gradient(circle, ${hexToRgba(accent, 0.24)}, transparent 60%)`,
      filter: "blur(24px)",
      pointerEvents: "none",
      transform: "translate3d(0,0,0)",
    },
    heroTop: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
      flexWrap: "wrap",
      marginBottom: 16,
      position: "relative",
      zIndex: 1,
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 14px",
      borderRadius: 999,
      background: "rgba(255,255,255,0.06)",
      border: PANEL_BORDER,
      color: TEXT_MAIN,
      fontSize: 12,
      fontWeight: 800,
      letterSpacing: "0.02em",
      boxShadow: "0 8px 20px rgba(0,0,0,0.18)",
    },
    badgeAccent: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 14px",
      borderRadius: 999,
      background: isPro ? "rgba(76,175,122,0.16)" : "rgba(255,255,255,0.05)",
      border: isPro ? "1px solid rgba(76,175,122,0.28)" : PANEL_BORDER,
      color: isPro ? "#78efb0" : TEXT_MAIN,
      fontSize: 12,
      fontWeight: 800,
      boxShadow: "0 8px 20px rgba(0,0,0,0.16)",
    },
    heroTitle: {
      fontSize: mobile ? 34 : 48,
      fontWeight: 950,
      letterSpacing: "-0.06em",
      lineHeight: 1.02,
      maxWidth: 580,
      marginBottom: 12,
      position: "relative",
      zIndex: 1,
      color: TEXT_MAIN,
    },
    heroSub: {
      fontSize: mobile ? 15 : 16,
      lineHeight: 1.6,
      color: TEXT_MUTED,
      maxWidth: 740,
      position: "relative",
      zIndex: 1,
    },
    heroMetrics: {
      display: "grid",
      gridTemplateColumns: mobile ? "1fr 1fr" : "repeat(3, minmax(0, 1fr))",
      gap: 12,
      marginTop: 24,
      position: "relative",
      zIndex: 1,
    },
    metricCard: {
      borderRadius: 22,
      padding: 16,
      background: "rgba(0,0,0,0.22)",
      border: "1px solid rgba(255,255,255,0.05)",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.04)",
    },
    metricValue: {
      fontSize: mobile ? 22 : 26,
      fontWeight: 900,
      letterSpacing: "-0.04em",
      lineHeight: 1,
      color: TEXT_MAIN,
    },
    metricLabel: {
      fontSize: 12,
      color: TEXT_MUTED,
      marginTop: 6,
      fontWeight: 500,
    },
    compactHero: {
      borderRadius: 30,
      padding: mobile ? 20 : 26,
      background: GLASS_BG,
      border: PANEL_BORDER,
      boxShadow: "0 28px 72px rgba(0,0,0,0.34)",
      backdropFilter: "blur(34px) saturate(150%)",
      overflow: "hidden",
      position: "relative",
    },
    compactTitle: {
      fontSize: mobile ? 24 : 30,
      fontWeight: 950,
      letterSpacing: "-0.05em",
      lineHeight: 1,
      marginTop: 10,
      color: TEXT_MAIN,
    },
    compactSub: {
      marginTop: 10,
      fontSize: mobile ? 14 : 15,
      lineHeight: 1.6,
      color: TEXT_MUTED,
      maxWidth: 760,
    },
    compactActionRow: {
      marginTop: 16,
      display: "flex",
      gap: 10,
      flexWrap: "wrap",
    },
    compactButton: {
      border: 0,
      borderRadius: 16,
      padding: "12px 18px",
      background: TEXT_MAIN,
      color: "#0b0d12",
      fontWeight: 900,
      boxShadow: "0 8px 20px rgba(255,255,255,0.12)",
      cursor: "pointer",
    },
    compactGhost: {
      border: PANEL_BORDER,
      borderRadius: 16,
      padding: "12px 18px",
      background: "rgba(255,255,255,0.05)",
      color: TEXT_MAIN,
      fontWeight: 800,
      boxShadow: "0 8px 20px rgba(0,0,0,0.2)",
      cursor: "pointer",
    },
    statusRow: {
      display: "flex",
      flexWrap: "wrap",
      gap: 10,
      alignItems: "center",
      padding: "0 4px",
    },
    pill: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 14px",
      borderRadius: 999,
      border: PANEL_BORDER,
      background: "rgba(20,22,32,0.68)",
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: 600,
      backdropFilter: "blur(12px)",
      boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    },
    pillAction: {
      border: PANEL_BORDER,
      background: "rgba(255,255,255,0.08)",
      color: TEXT_MAIN,
      padding: "8px 14px",
      borderRadius: 999,
      fontSize: 12,
      fontWeight: 700,
      boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
      cursor: "pointer",
    },
    memoryCard: {
      borderRadius: 26,
      padding: 18,
      background: "linear-gradient(180deg, rgba(35, 26, 44, 0.84), rgba(15, 15, 22, 0.88))",
      border: "1px solid rgba(255,255,255,0.08)",
      boxShadow: "0 24px 64px rgba(0,0,0,0.36)",
      backdropFilter: "blur(34px) saturate(150%)",
      display: "grid",
      gap: 14,
      position: "relative",
      overflow: "hidden",
    },
    memoryHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      flexWrap: "wrap",
    },
    memoryTitleWrap: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      minWidth: 0,
    },
    memoryIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      display: "grid",
      placeItems: "center",
      background: `linear-gradient(180deg, ${hexToRgba(accent, 0.32)}, rgba(255,255,255,0.08))`,
      color: TEXT_MAIN,
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.14)",
      flex: "0 0 auto",
      fontSize: 18,
    },
    memoryTitle: {
      fontSize: 16,
      fontWeight: 900,
      letterSpacing: "-0.03em",
      color: TEXT_MAIN,
    },
    memoryMeta: {
      fontSize: 12,
      color: TEXT_MUTED,
      marginTop: 2,
    },
    memoryUpdated: {
      fontSize: 12,
      color: TEXT_MUTED,
      whiteSpace: "nowrap",
    },
    memoryQuote: {
      borderRadius: 20,
      padding: 16,
      background: "rgba(0,0,0,0.28)",
      color: "rgba(255,255,255,0.88)",
      border: "1px solid rgba(255,255,255,0.05)",
      lineHeight: 1.6,
      fontSize: 14,
      fontStyle: "italic",
      whiteSpace: "pre-wrap",
    },
    memoryGlow: {
      position: "absolute",
      inset: "auto auto -10% 82%",
      width: 150,
      height: 150,
      borderRadius: 999,
      background: `radial-gradient(circle, ${hexToRgba(accent, 0.24)}, transparent)`,
      filter: "blur(20px)",
      pointerEvents: "none",
    },
    moodSection: {
      display: "grid",
      gap: 10,
      padding: "0 4px",
    },
    moodHeading: {
      fontSize: 18,
      fontWeight: 900,
      letterSpacing: "-0.04em",
      color: TEXT_MAIN,
    },
    moodSub: {
      fontSize: 13,
      color: TEXT_MUTED,
      lineHeight: 1.5,
    },
    moodRow: {
      display: "grid",
      gridTemplateColumns: mobile ? "repeat(2, minmax(0, 1fr))" : "repeat(4, minmax(0, 1fr))",
      gap: 12,
    },
    moodButton: {
      position: "relative",
      border: PANEL_BORDER,
      borderRadius: 20,
      padding: "16px 12px",
      background: "rgba(30,32,44,0.42)",
      color: TEXT_MUTED,
      display: "grid",
      gap: 6,
      justifyItems: "center",
      boxShadow: "0 8px 24px rgba(0,0,0,0.2)",
      overflow: "hidden",
      cursor: "pointer",
      backdropFilter: "blur(16px)",
      transition:
        "background 420ms ease, box-shadow 420ms ease, border-color 420ms ease, color 420ms ease, transform 420ms ease",
    },
    moodButtonActive: {
      position: "relative",
      border: `1px solid ${hexToRgba(accent, 0.72)}`,
      borderRadius: 20,
      padding: "16px 12px",
      background: "rgba(18,20,28,0.84)",
      color: TEXT_MAIN,
      display: "grid",
      gap: 6,
      justifyItems: "center",
      boxShadow: `0 0 0 1px ${hexToRgba(accent, 0.18)} inset, 0 12px 32px rgba(0,0,0,0.3), 0 0 20px ${hexToRgba(
        accent,
        0.24
      )}`,
      overflow: "hidden",
      cursor: "pointer",
      backdropFilter: "blur(16px)",
      transition:
        "background 420ms ease, box-shadow 420ms ease, border-color 420ms ease, color 420ms ease, transform 420ms ease",
    },
    moodIcon: {
      fontSize: 22,
      lineHeight: 1,
    },
    moodLabel: {
      fontSize: 14,
      fontWeight: 900,
      letterSpacing: "-0.02em",
    },
    moodLabelSub: {
      fontSize: 11,
      opacity: 0.74,
    },
    moodGlow: {
      position: "absolute",
      inset: "auto -20% -30% auto",
      width: 100,
      height: 100,
      borderRadius: 999,
      background: `radial-gradient(circle, ${hexToRgba(accent, 0.38)}, transparent)`,
      filter: "blur(10px)",
      pointerEvents: "none",
    },
    aiPanel: {
      borderRadius: 26,
      padding: 16,
      background: GLASS_BG,
      border: PANEL_BORDER,
      boxShadow: "0 24px 64px rgba(0,0,0,0.34)",
      backdropFilter: "blur(34px) saturate(150%)",
      display: "grid",
      gap: 14,
      transition:
        "background 420ms ease, box-shadow 420ms ease, border-color 420ms ease, color 420ms ease, transform 420ms ease",
    },
    aiHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      flexWrap: "wrap",
    },
    aiHeaderLeft: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      minWidth: 0,
    },
    aiDot: {
      width: 12,
      height: 12,
      borderRadius: 999,
      background: loading ? "#64748b" : hasConversationStarted ? "#3bc6a1" : "#ff9e5e",
      boxShadow: loading
        ? "0 0 0 6px rgba(100,116,139,0.14)"
        : hasConversationStarted
          ? "0 0 0 6px rgba(59,198,161,0.14)"
          : "0 0 0 6px rgba(255,158,94,0.14)",
      flex: "0 0 auto",
    },
    aiTitle: {
      fontSize: 16,
      fontWeight: 900,
      letterSpacing: "-0.03em",
      lineHeight: 1.15,
      color: TEXT_MAIN,
    },
    aiSub: {
      marginTop: 2,
      fontSize: 13,
      color: TEXT_MUTED,
      lineHeight: 1.4,
    },
    aiChips: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap",
    },
    aiChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "7px 12px",
      borderRadius: 999,
      background: "rgba(0,0,0,0.28)",
      border: "1px solid rgba(255,255,255,0.06)",
      fontSize: 12,
      color: "rgba(255,255,255,0.82)",
      fontWeight: 700,
    },
    threadCard: {
      display: "flex",
      flexDirection: "column",
      borderRadius: 34,
      background: "linear-gradient(180deg, rgba(20,22,32,0.72), rgba(11,13,18,0.86))",
      border: PANEL_BORDER,
      boxShadow: "0 32px 80px rgba(0,0,0,0.52)",
      overflow: "hidden",
      backdropFilter: "blur(40px) saturate(150%)",
      minHeight: mobile ? 400 : 560,
      maxHeight: 600,
      position: "relative",
      transition:
        "background 420ms ease, box-shadow 420ms ease, border-color 420ms ease, color 420ms ease, transform 420ms ease",
    },
    threadGlow: {
      position: "absolute",
      inset: "-20% auto auto -20%",
      width: 300,
      height: 300,
      borderRadius: 999,
      background: "radial-gradient(circle, rgba(255,255,255,0.06), transparent)",
      filter: "blur(18px)",
      pointerEvents: "none",
      zIndex: 0,
    },
    threadHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      padding: 16,
      borderBottom: "1px solid rgba(255,255,255,0.06)",
      background: "rgba(255,255,255,0.03)",
      backdropFilter: "blur(14px)",
      position: "relative",
      zIndex: 1,
    },
    threadLeft: {
      display: "flex",
      alignItems: "center",
      gap: 12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 16,
      background: "linear-gradient(135deg, #2a2d3e, #141620)",
      color: TEXT_MAIN,
      display: "grid",
      placeItems: "center",
      fontSize: 15,
      fontWeight: 900,
      boxShadow: "0 8px 16px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.1)",
      border: "1px solid rgba(255,255,255,0.05)",
    },
    threadText: {
      display: "flex",
      flexDirection: "column",
      gap: 2,
    },
    threadName: {
      fontSize: 16,
      fontWeight: 900,
      letterSpacing: "-0.03em",
      color: TEXT_MAIN,
    },
    threadMeta: {
      fontSize: 12,
      color: TEXT_MUTED,
    },
    liveChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 12px",
      borderRadius: 999,
      background: "rgba(0,0,0,0.22)",
      border: "1px solid rgba(255,255,255,0.05)",
      fontSize: 12,
      color: "rgba(255,255,255,0.82)",
      boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    },
    liveDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      background: isPro ? "#4caf7a" : "#ff9e5e",
      boxShadow: isPro ? "0 0 0 4px rgba(76,175,122,0.2)" : "0 0 0 4px rgba(255,158,94,0.2)",
    },
    threadBody: {
      flex: "1 1 auto",
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
      padding: mobile ? 14 : 20,
      position: "relative",
      zIndex: 1,
      overflowY: "auto",
      scrollbarWidth: "none",
      msOverflowStyle: "none",
    },
    stream: {
      display: "flex",
      flexDirection: "column",
      gap: 16,
      paddingBottom: 4,
    },
    messageRow: {
      display: "flex",
      width: "100%",
    },
    messageBubble: {
      maxWidth: mobile ? "90%" : "75%",
      minWidth: 0,
      padding: "14px 16px",
      borderRadius: 24,
      fontSize: mobile ? 14 : 15,
      lineHeight: 1.5,
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
      overflowWrap: "anywhere",
      letterSpacing: "-0.005em",
      position: "relative",
      boxSizing: "border-box",
      backdropFilter: "blur(20px)",
      userSelect: "none",
      WebkitUserSelect: "none",
    },
    meBubble: {
      background: "rgba(40,44,60,0.75)",
      color: TEXT_MAIN,
      boxShadow: "0 12px 24px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.05)",
      border: "1px solid rgba(255,255,255,0.05)",
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 8,
    },
    futureMeBubble: {
      background: "rgba(255,255,255,0.09)",
      color: TEXT_MAIN,
      border: "1px solid rgba(255,255,255,0.10)",
      boxShadow: "0 12px 24px rgba(0,0,0,0.2)",
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomLeftRadius: 8,
      borderBottomRightRadius: 24,
    },
    messageTop: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      marginBottom: 8,
    },
    messageRole: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "6px 10px",
      borderRadius: 999,
      fontSize: 11,
      fontWeight: 900,
      letterSpacing: "0.02em",
      background: "rgba(255,255,255,0.10)",
      color: "rgba(255,255,255,0.90)",
    },
    messageRoleMe: {
      background: "rgba(0,0,0,0.28)",
      color: TEXT_MUTED,
    },
    copyButton: {
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: 999,
      padding: "6px 12px",
      background: "rgba(255,255,255,0.05)",
      color: TEXT_MAIN,
      fontSize: 11,
      fontWeight: 800,
      cursor: "pointer",
    },
    messageText: {
      fontSize: mobile ? 14 : 15,
      lineHeight: 1.6,
      whiteSpace: "pre-wrap",
      overflowWrap: "anywhere",
      color: "rgba(255,255,255,0.92)",
    },
    timestamp: {
      marginTop: 10,
      fontSize: 11,
      color: TEXT_MUTED,
      textAlign: "right",
    },
    typingRow: {
      display: "flex",
      justifyContent: "flex-start",
    },
    typingBubble: {
      padding: "14px 16px",
      borderRadius: 24,
      background: "rgba(255,255,255,0.05)",
      color: TEXT_MUTED,
      fontSize: 14,
      border: "1px solid rgba(255,255,255,0.05)",
      animation: "pulse 1.3s ease-in-out infinite",
    },
    typingDots: {
      display: "inline-flex",
      gap: 6,
      alignItems: "center",
    },
    typingDot: {
      width: 6,
      height: 6,
      borderRadius: 999,
      background: "currentColor",
      opacity: 0.8,
    },
    composerShell: {
      flex: "0 0 auto",
      borderRadius: 26,
      background: "rgba(20,22,32,0.62)",
      border: PANEL_BORDER,
      boxShadow: "0 -10px 40px rgba(0,0,0,0.3)",
      backdropFilter: "blur(40px) saturate(150%)",
      overflow: "hidden",
      position: "relative",
      transition:
        "background 420ms ease, box-shadow 420ms ease, border-color 420ms ease, color 420ms ease, transform 420ms ease",
    },
    composerTop: {
      display: "flex",
      justifyContent: "space-between",
      gap: 10,
      flexWrap: "wrap",
      padding: "14px 16px 0",
    },
    composerChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "7px 12px",
      borderRadius: 999,
      background: "rgba(0,0,0,0.24)",
      color: TEXT_MUTED,
      border: "1px solid rgba(255,255,255,0.05)",
      fontSize: 12,
      fontWeight: 800,
    },
    composerRow: {
      display: "flex",
      gap: 10,
      alignItems: "flex-end",
      padding: 14,
      flexDirection: mobile ? "column" : "row",
    },
    composerTextarea: {
      flex: 1,
      width: "100%",
      minHeight: 52,
      maxHeight: 160,
      resize: "none",
      borderRadius: 20,
      border: "1px solid rgba(255,255,255,0.10)",
      background: "rgba(0,0,0,0.24)",
      color: TEXT_MAIN,
      padding: "14px 16px",
      lineHeight: 1.45,
      fontSize: 15,
      outline: "none",
      boxShadow: "inset 0 2px 4px rgba(0,0,0,0.2)",
      transition:
        "border-color 420ms ease, box-shadow 420ms ease, background 420ms ease, color 420ms ease",
    },
    sendButton: {
      minWidth: mobile ? "100%" : 110,
      border: 0,
      borderRadius: 20,
      padding: "14px 20px",
      background: `linear-gradient(180deg, ${accent}, ${hexToRgba(accent, 0.82)})`,
      color: "#ffffff",
      fontWeight: 900,
      fontSize: 15,
      boxShadow: `0 8px 20px ${hexToRgba(accent, 0.24)}, inset 0 1px 0 rgba(255,255,255,0.18)`,
      cursor: "pointer",
      transition: "transform 160ms ease, box-shadow 160ms ease, opacity 160ms ease",
    },
    micButton: {
      width: mobile ? "100%" : 48,
      minWidth: mobile ? "100%" : 48,
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: 20,
      padding: "14px 0",
      background: loading ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.22)",
      color: TEXT_MAIN,
      fontWeight: 900,
      fontSize: 15,
      boxShadow: "0 8px 20px rgba(0,0,0,0.18)",
      cursor: "pointer",
    },
    helper: {
      padding: "0 16px 16px",
      fontSize: 12,
      color: TEXT_MUTED,
      lineHeight: 1.5,
      textAlign: "center",
    },
    sheetBackdrop: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.62)",
      backdropFilter: "blur(8px)",
      zIndex: 40,
    },
    sheet: {
      position: "fixed",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 50,
      background: "rgba(18,20,30,0.96)",
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      borderTop: PANEL_BORDER,
      padding: 24,
      boxShadow: "0 -24px 80px rgba(0,0,0,0.5)",
      display: "grid",
      gap: 16,
      backdropFilter: "blur(40px) saturate(150%)",
      color: TEXT_MAIN,
    },
    sheetTitle: {
      fontSize: 22,
      fontWeight: 900,
      letterSpacing: "-0.03em",
    },
    sheetSub: {
      marginTop: 4,
      fontSize: 14,
      color: TEXT_MUTED,
      lineHeight: 1.5,
    },
    sheetGroup: {
      display: "grid",
      gap: 10,
    },
    sheetButton: {
      width: "100%",
      textAlign: "left",
      borderRadius: 16,
      padding: "16px",
      border: "1px solid rgba(255,255,255,0.05)",
      background: "rgba(255,255,255,0.03)",
      color: TEXT_MAIN,
      fontWeight: 800,
      fontSize: 15,
      cursor: "pointer",
    },
    paywallBackdrop: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.68)",
      backdropFilter: "blur(12px)",
      zIndex: 60,
    },
    paywall: {
      position: "fixed",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 70,
      background: "rgba(18,20,30,0.98)",
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      borderTop: "1px solid rgba(255,255,255,0.10)",
      padding: 24,
      boxShadow: "0 -24px 100px rgba(0,0,0,0.6)",
      display: "grid",
      gap: 16,
      backdropFilter: "blur(40px) saturate(150%)",
      color: TEXT_MAIN,
    },
    paywallHeader: {
      display: "grid",
      gap: 6,
    },
    paywallTitle: {
      fontSize: 24,
      fontWeight: 950,
      letterSpacing: "-0.04em",
      color: TEXT_MAIN,
    },
    paywallSub: {
      fontSize: 14,
      lineHeight: 1.5,
      color: "rgba(255,255,255,0.80)",
    },
    featureCard: {
      borderRadius: 20,
      padding: 16,
      background: "rgba(0,0,0,0.28)",
      border: "1px solid rgba(255,255,255,0.05)",
    },
    featureList: {
      display: "grid",
      gap: 12,
      marginTop: 8,
    },
    featureItem: {
      display: "flex",
      alignItems: "flex-start",
      gap: 12,
      fontSize: 14,
      lineHeight: 1.5,
      color: TEXT_MAIN,
    },
    featureDot: {
      width: 8,
      height: 8,
      marginTop: 6,
      borderRadius: 999,
      background: accent,
      flex: "0 0 auto",
      boxShadow: `0 0 10px ${hexToRgba(accent, 0.5)}`,
    },
    paywallButtons: {
      display: "flex",
      gap: 12,
      flexWrap: "wrap",
    },
    proButton: {
      border: 0,
      borderRadius: 16,
      padding: "16px",
      background: `linear-gradient(180deg, ${accent}, ${hexToRgba(accent, 0.82)})`,
      color: "#050507",
      fontWeight: 900,
      fontSize: 15,
      boxShadow: `0 12px 24px ${hexToRgba(accent, 0.3)}`,
      cursor: "pointer",
      flex: 1,
      minWidth: "100%",
    },
    ghostButton: {
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: 16,
      padding: "14px 16px",
      background: "rgba(255,255,255,0.05)",
      color: TEXT_MAIN,
      fontWeight: 800,
      cursor: "pointer",
      flex: 1,
      minWidth: mobile ? "100%" : "calc(50% - 6px)",
    },
    hintLine: {
      fontSize: 12,
      color: TEXT_MUTED,
      lineHeight: 1.5,
      textAlign: "center",
      marginTop: 8,
    },
    freeTag: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 14px",
      borderRadius: 999,
      background: isPro ? "rgba(76,175,122,0.18)" : "rgba(255,255,255,0.08)",
      color: isPro ? "#78efb0" : TEXT_MAIN,
      border: isPro ? "1px solid rgba(76,175,122,0.28)" : "1px solid rgba(255,255,255,0.10)",
      fontSize: 13,
      fontWeight: 800,
      width: "fit-content",
    },
    sheetInput: {
      borderRadius: 16,
      border: "1px solid rgba(255,255,255,0.10)",
      padding: "16px",
      background: "rgba(0,0,0,0.32)",
      color: TEXT_MAIN,
      fontSize: 16,
      outline: "none",
    },
    sheetPrimary: {
      border: 0,
      borderRadius: 16,
      padding: "16px",
      background: TEXT_MAIN,
      color: "#08080c",
      fontWeight: 900,
      fontSize: 15,
      cursor: "pointer",
    },
    sheetSecondary: {
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: 16,
      padding: "16px",
      background: "rgba(255,255,255,0.05)",
      color: TEXT_MAIN,
      fontWeight: 800,
      fontSize: 15,
      cursor: "pointer",
    },
    sheetHint: {
      fontSize: 13,
      color: TEXT_MUTED,
      lineHeight: 1.5,
      textAlign: "center",
    },
    insightsGrid: {
      display: "grid",
      gridTemplateColumns: mobile ? "1fr" : "1.2fr 0.8fr",
      gap: 14,
    },
    insightCard: {
      borderRadius: 26,
      padding: 18,
      background: GLASS_BG,
      border: PANEL_BORDER,
      boxShadow: "0 24px 64px rgba(0,0,0,0.34)",
      backdropFilter: "blur(34px) saturate(150%)",
    },
    insightTitle: {
      fontSize: 18,
      fontWeight: 900,
      letterSpacing: "-0.04em",
      marginBottom: 8,
    },
    insightSub: {
      fontSize: 13,
      color: TEXT_MUTED,
      lineHeight: 1.5,
    },
    sparkWrap: {
      display: "grid",
      gap: 10,
      marginTop: 14,
    },
    sparkBars: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      gap: 8,
      alignItems: "end",
      minHeight: 140,
    },
    sparkBar: {
      borderRadius: 14,
      background: "rgba(255,255,255,0.10)",
      border: "1px solid rgba(255,255,255,0.06)",
      minHeight: 12,
      position: "relative",
      overflow: "hidden",
    },
    sparkFill: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 14,
      background: `linear-gradient(180deg, ${accent}, ${hexToRgba(accent, 0.5)})`,
      boxShadow: `0 0 18px ${hexToRgba(accent, 0.22)}`,
    },
    sparkLabelRow: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      gap: 8,
      fontSize: 11,
      color: TEXT_MUTED,
    },
    miniCards: {
      display: "grid",
      gridTemplateColumns: mobile ? "1fr 1fr" : "repeat(2, minmax(0, 1fr))",
      gap: 10,
    },
    miniCard: {
      borderRadius: 20,
      padding: 14,
      background: "rgba(0,0,0,0.24)",
      border: "1px solid rgba(255,255,255,0.06)",
    },
    miniValue: {
      fontSize: 22,
      fontWeight: 900,
      letterSpacing: "-0.04em",
    },
    miniLabel: {
      fontSize: 12,
      color: TEXT_MUTED,
      marginTop: 4,
    },
    themeBubbleContainer: {
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
      padding: "10px 0",
    },
    themeBubble: {
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: `linear-gradient(135deg, ${accent}, ${hexToRgba(accent, 0.6)})`,
      color: "#fff",
      fontWeight: 800,
      fontSize: 12,
      boxShadow: `0 8px 24px ${hexToRgba(accent, 0.3)}`,
      textAlign: "center",
      border: "1px solid rgba(255,255,255,0.15)",
      transition: "transform 0.2s ease",
      userSelect: "none",
    },
    voiceHint: {
      fontSize: 12,
      color: TEXT_MUTED,
      lineHeight: 1.5,
      marginTop: 8,
    },
    memoryPills: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap",
      marginTop: 12,
    },
    memoryPill: {
      borderRadius: 999,
      padding: "8px 12px",
      background: "rgba(255,255,255,0.06)",
      border: "1px solid rgba(255,255,255,0.06)",
      color: TEXT_MAIN,
      fontSize: 12,
      fontWeight: 700,
    },
    scrollBottomBtn: {
      position: "absolute",
      bottom: 24,
      right: 24,
      width: 44,
      height: 44,
      borderRadius: "50%",
      background: GLASS_BG,
      border: PANEL_BORDER,
      color: TEXT_MAIN,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
      backdropFilter: "blur(20px)",
      cursor: "pointer",
      zIndex: 10,
      fontSize: 18,
    },
    contextMenu: {
      position: "fixed",
      zIndex: 100,
      background: "rgba(24, 26, 38, 0.95)",
      backdropFilter: "blur(20px)",
      border: PANEL_BORDER,
      borderRadius: 16,
      padding: 8,
      display: "flex",
      flexDirection: "column",
      gap: 4,
      boxShadow: "0 12px 40px rgba(0,0,0,0.6)",
      minWidth: 220,
    },
    contextMenuBtn: {
      background: "transparent",
      border: "none",
      color: TEXT_MAIN,
      textAlign: "left",
      padding: "10px 14px",
      fontSize: 14,
      fontWeight: 600,
      borderRadius: 10,
      cursor: "pointer",
    },
    contextMenuBtnDanger: {
      color: "#fb7185",
    },
    focusModeOverlay: {
      position: "fixed",
      inset: 0,
      zIndex: 9999,
      background: "rgba(9, 9, 13, 0.98)",
      backdropFilter: "blur(20px)",
      display: "flex",
      flexDirection: "column",
      padding: mobile ? 20 : 40,
    },
    focusModeHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    focusModeTitle: {
      fontSize: 20,
      fontWeight: 800,
      color: TEXT_MUTED,
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
    focusModeClose: {
      background: "rgba(255,255,255,0.05)",
      border: PANEL_BORDER,
      color: TEXT_MAIN,
      width: 40,
      height: 40,
      borderRadius: 20,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
    },
    focusModeTextarea: {
      flex: 1,
      width: "100%",
      background: "transparent",
      border: "none",
      color: TEXT_MAIN,
      fontSize: mobile ? 22 : 32,
      lineHeight: 1.4,
      outline: "none",
      resize: "none",
    },
    focusModeFooter: {
      marginTop: 20,
      display: "flex",
      justifyContent: "flex-end",
    },
    memoryJourney: {
      borderRadius: 26,
      padding: 18,
      background: GLASS_BG,
      border: PANEL_BORDER,
      boxShadow: "0 24px 64px rgba(0,0,0,0.34)",
      backdropFilter: "blur(34px) saturate(150%)",
      display: "grid",
      gap: 14,
    },
    journeyTrack: {
      position: "relative",
      minHeight: 180,
      borderRadius: 22,
      background: "rgba(0,0,0,0.22)",
      overflow: "hidden",
      border: "1px solid rgba(255,255,255,0.06)",
    },
    journeyGlow: {
      position: "absolute",
      inset: 0,
      background: `radial-gradient(circle at 50% 60%, ${hexToRgba(accent, 0.22)}, transparent 52%)`,
      pointerEvents: "none",
    },
    journeyPath: {
      position: "absolute",
      inset: "20px 18px",
      borderRadius: 999,
      border: "1px dashed rgba(255,255,255,0.15)",
    },
    journeyNode: {
      position: "absolute",
      width: 18,
      height: 18,
      borderRadius: 999,
      background: accent,
      boxShadow: `0 0 18px ${hexToRgba(accent, 0.35)}`,
    },
  };
}

export const themeKeywords = {
  work: ["work", "job", "career", "project", "build", "school", "study", "exam", "code", "app"],
  relationships: ["friend", "friends", "family", "mother", "father", "sister", "brother", "love", "relationship"],
  fear: ["fear", "anxious", "anxiety", "worry", "scared", "afraid", "stress", "nervous"],
  growth: ["grow", "better", "future", "improve", "learn", "progress", "change", "discipline"],
  freedom: ["free", "freedom", "choice", "independent", "own", "myself", "control"],
};

export function searchThemes(messages: { role: string; text: string }[]) {
  const joined = messages
    .filter((m) => m.role === "me")
    .map((m) => m.text.toLowerCase())
    .join(" ");

  const results = Object.entries(themeKeywords).map(([label, keywords]) => {
    const count = keywords.reduce((sum, keyword) => {
      const matches = joined.split(keyword).length - 1;
      return sum + matches;
    }, 0);
    return { label, count };
  });

  return results
    .filter((item) => item.count > 0)
    .sort((a, b) => b.count - a.count)
    .slice(0, 4);
}
